name: linting, testing, building
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on:
    push:
        branches: [master]
    pull_request:
        branches: [master]
jobs:
    apptesting:
        runs-on: ubuntu-latest
        strategy:
            matrix:
                node-version: [18.x]
        steps:
            - uses: actions/checkout@v2
            - name: Setup Node.js ${{matrix.node-version}} environment
              uses: actions/setup-node@v1
              with:
                  node-version: ${{ matrix.node-version }}
            - name: Installing modules...
              run: npm install
            - name: Building production project...
              run: npm run build:prod
            - name: Lint typescript
              run: npm run lint:ts
              if: always()
            - name: Lint scss
              run: npm run lint:scss
              if: always()
            - name: unit tests
              run: npm run test:unit
              if: always()
            #   problems with loki, change in package.json/loki/target 'chrome.app' - to test on local machine and 'chome.docker' - to test on github actions
            # - name: build storybook
            #   run: npm run storybook:build
            #   if: always()
            # - name: screenshot testing
            #   run: npm run test:ui:ci
            #   if: always()
